version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.7.0 
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@8"
      - restore_cache:
          key: dependency-cache3-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache3-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code style check
          command: npm run format-check
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Testing
          command: npm run test-ci
      - run:
          name: Publish
          command: |
            npx expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}  
            export CI=1
            npx expo publish --quiet --release-channel default
